export const getAuth = () => Promise.resolve();
export const createUserWithEmailAndPassword = () => Promise.resolve();
export const signInWithEmailAndPassword = () => Promise.resolve();
export const GoogleAuthProvider = () => Promise.resolve();
export const signInWithPopup = () => Promise.resolve();
export const signOut = () => Promise.resolve();
export const onAuthStateChanged = () => Promise.resolve();

export const getFirestore = () => Promise.resolve();
export const collection = () => Promise.resolve();
export const addDoc = () => Promise.resolve();
export const getDocs = () => Promise.resolve();
export const updateDoc = () => Promise.resolve();
export const orderBy = () => Promise.resolve();
export const query = () => Promise.resolve();
export const arrayUnion = () => Promise.resolve();
export const arrayRemove = () => Promise.resolve();
export const doc = () => Promise.resolve();
export const deleteDoc = () => Promise.resolve();
